"""subscriptions

Revision ID: 3f08854ccd2a
Revises: 8ed62ac8cd01
Create Date: 2026-06-04 15:28:48.952483
"""
from alembic import op
import sqlalchemy as sa


revision = '3f08854ccd2a'
down_revision = '8ed62ac8cd01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('linear_issue_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'linear_issue_id', name='uq_subscription')
    )
    op.create_index(op.f('ix_subscriptions_linear_issue_id'), 'subscriptions', ['linear_issue_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_telegram_id'), 'subscriptions', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_telegram_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_linear_issue_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
