"""init

Revision ID: 444ddc150899
Revises: 
Create Date: 2026-06-03 12:10:25.560831
"""
from alembic import op
import sqlalchemy as sa


revision = '444ddc150899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_bindings',
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('linear_team_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_chat_id')
    )
    op.create_table('issue_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('linear_issue_id', sa.String(length=64), nullable=False),
    sa.Column('linear_issue_identifier', sa.String(length=32), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_links_linear_issue_id'), 'issue_links', ['linear_issue_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_name', sa.String(length=128), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=256), nullable=True),
    sa.Column('app_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('linear_label', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('role', sa.Enum('member', 'lead', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('webhook_dedup',
    sa.Column('delivery_id', sa.String(length=128), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_dedup')
    op.drop_table('users')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_issue_links_linear_issue_id'), table_name='issue_links')
    op.drop_table('issue_links')
    op.drop_table('chat_bindings')
    # ### end Alembic commands ###
