"""add registered flag

Revision ID: 4aa23b7596de
Revises: 444ddc150899
Create Date: 2026-06-03 15:35:38.238723
"""
from alembic import op
import sqlalchemy as sa


revision = '4aa23b7596de'
down_revision = '444ddc150899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'registered',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered')
    # ### end Alembic commands ###
