"""projects and project_leads

Revision ID: e649e1d14137
Revises: 4aa23b7596de
Create Date: 2026-06-03 15:41:26.996841
"""
from alembic import op
import sqlalchemy as sa


revision = 'e649e1d14137'
down_revision = '4aa23b7596de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'project_id', name='uq_lead_project')
    )
    op.create_index(op.f('ix_project_leads_project_id'), 'project_leads', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_leads_telegram_id'), 'project_leads', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_leads_telegram_id'), table_name='project_leads')
    op.drop_index(op.f('ix_project_leads_project_id'), table_name='project_leads')
    op.drop_table('project_leads')
    op.drop_table('projects')
    # ### end Alembic commands ###
